pub enum Text<'a> {
    Settings,
    Affinities,
    CodeNow,
    Schedule,
    Security,
    Messages,
    AffinitiesTableDescription,
    NoMatchingUsersFound,
    ExtendYourLanguageSelection,
    YourCurrentWeeklySchedule,
    SetYourAvailability,
    YouHaventScheduled,
    ChatWith(&'a str),
    UserWithUnverifiedEmail,
    NoChatsYet,
    CodeNowTableDescription,
    ContactBestMatchingUsers,
    NoOnlineUsers,
    NoMatchingOnlineUsers,
    Add,
    PageNotFound(&'a str),
    UnknownPageNotFound,
    ExtendYourAvailability,
    NoAvailableUsers,
}

impl<'a> ToString for Text<'a> {
    fn to_string(&self) -> String {
        match self {
            Text::Settings => "Settings".into(),
            Text::Affinities => "Affinities".into(),
            Text::CodeNow => "Code Now".into(),
            Text::Schedule => "Schedule".into(),
            Text::Security => "Security".into(),
            Text::Messages => "Messages".into(),
            Text::AffinitiesTableDescription => "In the table below, you can see a list of developers who love the same languages as you. Just click the chat icon to start chatting and organize your next pair-programming session.".into(),
            Text::NoMatchingUsersFound => "Sorry, no matching users found. You can try to ".into(),
            Text::ExtendYourLanguageSelection => "extend your language selection.".into(),
            Text::YourCurrentWeeklySchedule => "Your current weekly schedule. Check your available hours. All hours are in UTC".into(),
            Text::SetYourAvailability => "Set your availability".into(),
            Text::YouHaventScheduled => "You haven't scheduled anything yet".into(),
            Text::ChatWith(name) => format!("Chat with {}", name),
            Text::UserWithUnverifiedEmail => "This user may not receive email notification of this message (email not verified yet)".into(),
            Text::NoChatsYet => "You don't have any chat yet".into(),
            Text::CodeNowTableDescription => "In the table below, you can see a list of online developers, sorted by analogy. Just click the chat icon to start chatting and organize your next pair-programming session.".into(),
            Text::ContactBestMatchingUsers => "contact any of best matching users.".into(),
            Text::NoOnlineUsers => "Sorry, no matching online users found. You can try to ".into(),
            Text::NoMatchingOnlineUsers => "Sorry, there are no online users now. You can try later or ".into(), 
            Text::Add => "Add".into(),
            Text::PageNotFound(page) => format!("Page {} not found", page),
            Text::UnknownPageNotFound => "Page not found".into(),
            Text::ExtendYourAvailability => "extend your availability.".into(),
            Text::NoAvailableUsers => "Sorry, there are no available users. You can try to ".into(),
        }
    }
}
