[package]
name = "devand-crypto"
version = "0.1.0"
authors = ["Alessandro Pezzato <alessandro@pezzato.net>"]
edition = "2018"

[dependencies]
log = "0.4"
jsonwebtoken = "7"
serde = {version = "1.0", features = ["derive"] }
