name: "devand-mailer docker image"

on:
  push:
    # branches:
    #   - master
    paths:
      - docker/devand-mailer/Dockerfile
      - devand-core/**
      - devand-mailer/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: alepez
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: devand-mailer
        dockerfile: docker/devand-mailer/Dockerfile
