name: "devand-run-env docker image"

on:
  schedule:
    - cron:  '0 4 * * *'
  push:
    paths:
      - docker/devand-run-env/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: alepez
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: devand-run-env
        dockerfile: docker/devand-run-env/Dockerfile
