name: "devand-web docker image"

on:
  push:
    branches:
      - master
    paths:
    - 'docker/devand-www/Dockerfile'
    - 'devand-core'
    - 'devand-db'
    - 'devand-ui'
    - 'devand-www'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: alepez
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: devand-web
        dockerfile: docker/devand-www/Dockerfile
