name: "devand-web-builder docker image"

on:
  push:
    branches:
      - master
    paths:
      - docker/devand-web-builder/Dockerfile
  schedule:
    - cron:  '0 4 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: alepez
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: devand-web-builder
        dockerfile: docker/devand-web-builder/Dockerfile
        push_image_and_stages: true
